### ISSUE TITLE
Avoid translation on server when source === target language

### ISSUE THREAD

**Issue by paulbalogh** [hypersay-events/curb#25]

**Comment by cdinu** [comment]
Don't know what actually is needed here, but I added a new condition here yesterday (not on production as of 29.06.22/11am). So it might be fixed.

https://github.com/hypersay-events/curb/blob/74562a88764bf59e5e908f799d635546b9777cfc/services/server/src/Translator.ts#L40

**Comment by ramiel** [comment]
This is probably the solution.
